[package]
name = "exercise_1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.26.2"
egui_plot = "0.26.2"
euclid = "0.22.9"
env_logger = "0.11.3"
